# Generated by Django 5.1.4 on 2025-01-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=200)),
                ('event_volunteer', models.IntegerField(default=0)),
                ('event_date', models.DateTimeField()),
            ],
        ),
    ]
